language: python
python:
  - "2.6"
  - "2.7"
# command to run tests
script: python centralserver/manage.py test
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
notifications:
  email:
    - ben@learningequality.org